// export const concertCardsData = [
//     {
//       concertDate: '5. maj',
//       concertLocation: 'Kayak Bar',
//       concertImage: 'concert_card_bg',
//       concertPrice: '100',
//       concertEvent: 'https://www.facebook.com/profile.php?id=61574049239842',
//       concertTarget: "_blank",
//       isConcertCancelled: true,
//       concertCancelOverlayImage: '/images/logos/hovednavn_logo-svg.svg',
//       concertCancelOverlayText: 'Koncert aflyst!',
//       concertLocationCoordinates: {
//         lat: 55.67552701830106,
//         lng: 12.58672489575173,
//       },
  
//     },
//     {
//       concertDate: '23. juni',
//       concertLocation: 'Pumpehuset',
//       concertImage: 'concert_card_bg',
//       concertPrice: '100',
//       isConcertCancelled: false,
//       concertCancelOverlayImage: '/images/logos/hovednavn_logo-svg.svg',
//       concertCancelOverlayText: 'Koncert aflyst!',
//       concertEvent: 'https://www.facebook.com/vschweitz',
//       concertTarget: "_blank",
//       concertLocationCoordinates: {
//         lat: 55.67739435279951,
//         lng: 12.565182724463128,
//       },
//       concertId: '2',
//     },
//     {
//       concertDate: '26. juli',
//       concertLocation: 'Loppen',
//       concertImage: 'concert_card_bg',
//       concertPrice: '130',
//       concertEvent: 'https://www.facebook.com/profile.php?id=61574049239842',
//       concertTarget: "_blank",
//       isConcertCancelled: false,
//       concertCancelOverlayImage: '/images/logos/hovednavn_logo-svg.svg',
//       concertCancelOverlayText: 'Koncert aflyst!',
//       concertLocationCoordinates: {
//         lat: 55.67389982358226,
//         lng: 12.597148928165135,
//       },
//       concertId: '3',
//     },
//     {
//       concertDate: '30. august',
//       concertLocation: 'Amager Bio',
//       concertImage: 'concert_card_bg',
//       concertPrice: '130',
//       concertEvent: 'https://www.facebook.com/profile.php?id=61574049239842',
//       concertTarget: "_blank",
//       isConcertCancelled: false,
//       concertCancelOverlayImage: '/images/logos/hovednavn_logo-svg.svg',
//       concertCancelOverlayText: 'Koncert aflyst!',
//       concertLocationCoordinates: {
//         lat: 55.65415790187533,
//         lng: 12.609199896636788,
//       },
//       concertId: '4',
//     },
// ]
